In [54]:
import numpy as np
from scipy.spatial import distance_matrix
from scipy.spatial import distance

a = np.array([[0,0], [1,1], [2,2], [3,3]])
b = np.array([[0,0], [-1,-1], [-2,-2], [-3,-3], [-4,-4]])

print("a.shape",a.shape)
print("b.shape",b.shape)
print('Euclidean')
print(distance_matrix(a, b))
print('Manhattan')
print(distance.cdist(a, b, 'cityblock'))


a.shape (4, 2)
b.shape (5, 2)
Euclidean
[[0.         1.41421356 2.82842712 4.24264069 5.65685425]
 [1.41421356 2.82842712 4.24264069 5.65685425 7.07106781]
 [2.82842712 4.24264069 5.65685425 7.07106781 8.48528137]
 [4.24264069 5.65685425 7.07106781 8.48528137 9.89949494]]
Manhattan
[[ 0.  2.  4.  6.  8.]
 [ 2.  4.  6.  8. 10.]
 [ 4.  6.  8. 10. 12.]
 [ 6.  8. 10. 12. 14.]]


# Euclidean Distance using broadcasting


In [11]:
# Euclidean Distance

np.linalg.norm(a[:, None, :] - b[None, :, :], axis=-1)

array([[0.        , 1.41421356, 2.82842712, 4.24264069, 5.65685425],
       [1.41421356, 2.82842712, 4.24264069, 5.65685425, 7.07106781],
       [2.82842712, 4.24264069, 5.65685425, 7.07106781, 8.48528137],
       [4.24264069, 5.65685425, 7.07106781, 8.48528137, 9.89949494]])

# Manhattan Distance using broadcasting

In [12]:
# Manhattan Distance

np.sum(np.abs(a[:, None, :] - b[None, :, :]), axis=-1)

array([[ 0,  2,  4,  6,  8],
       [ 2,  4,  6,  8, 10],
       [ 4,  6,  8, 10, 12],
       [ 6,  8, 10, 12, 14]])

In [17]:
def PointsDist(a,b):
    s = 0
    for i in range(len(a)):
        s += (a[i]-b[i])**2
    return np.sqrt(s)

In [20]:
a = np.array([1,1])
b = np.array([-1,-1])
PointsDist(a,b)

2.8284271247461903

In [65]:
np.random.seed(42)
a = np.random.randint(10, size=(10000,2))
b = np.random.randint(10, size=(10000,2))

In [66]:
print(distance.cdist(a, b, 'euclidean'))

[[1.41421356 1.         7.81024968 ... 4.12310563 3.60555128 3.        ]
 [2.         1.         8.06225775 ... 5.38516481 3.60555128 2.23606798]
 [5.09901951 5.         6.08276253 ... 8.06225775 3.60555128 3.        ]
 ...
 [4.12310563 5.09901951 3.16227766 ... 3.16227766 3.16227766 5.09901951]
 [3.         3.16227766 8.60232527 ... 3.16227766 5.09901951 5.09901951]
 [1.         1.41421356 5.83095189 ... 4.24264069 1.41421356 1.41421356]]


In [67]:
print(distance_matrix(a, b))

[[1.41421356 1.         7.81024968 ... 4.12310563 3.60555128 3.        ]
 [2.         1.         8.06225775 ... 5.38516481 3.60555128 2.23606798]
 [5.09901951 5.         6.08276253 ... 8.06225775 3.60555128 3.        ]
 ...
 [4.12310563 5.09901951 3.16227766 ... 3.16227766 3.16227766 5.09901951]
 [3.         3.16227766 8.60232527 ... 3.16227766 5.09901951 5.09901951]
 [1.         1.41421356 5.83095189 ... 4.24264069 1.41421356 1.41421356]]


In [68]:
print(np.linalg.norm(a[:, None, :] - b[None, :, :], axis=-1))

[[1.41421356 1.         7.81024968 ... 4.12310563 3.60555128 3.        ]
 [2.         1.         8.06225775 ... 5.38516481 3.60555128 2.23606798]
 [5.09901951 5.         6.08276253 ... 8.06225775 3.60555128 3.        ]
 ...
 [4.12310563 5.09901951 3.16227766 ... 3.16227766 3.16227766 5.09901951]
 [3.         3.16227766 8.60232527 ... 3.16227766 5.09901951 5.09901951]
 [1.         1.41421356 5.83095189 ... 4.24264069 1.41421356 1.41421356]]
